### PR TITLE
WIP:: Graph review and other things

### PR DESCRIPTION
**Pull request by fperignon**
- Try to fix  https://github.com/siconos/siconos/issues/184

- Bass guitar example implementation.

### CODE REVIEW

**Comment by vacary** [comment]
@fperignon  in 20061dd6dac321f6711b3365b67906daf6194d7c you remove SetNonSmoothDynamicalPtr() from Simulation class. It seems that it breaks the tests.

Is there any reasons to remove this method ?

**Comment by vacary** [comment]
This PR breaks more than 40 examples. In particular, the method fillW tries to fill a matrix with null pointers on siconosMatrix.

I think this is not reasonable to merge in this form. Perhaps, It would be better the create a branch with the commits (using cherry pick) that concerns only the Kernel and the computation of blocks. Everything is mixed in this PR and renders very difficult to follow the modifications,

**Comment by radarsat1** [comment]
Along with @vacary,  I recommend squashing this locally to one commit and using `git log -p` to select the parts that go semantically together. (e.g. separate commits or PRs for changes to the kernel, changes to music stuff, etc.)

**Comment by vacary** [comment]
Do you think that we will be able to merge this branch soon ?

**Comment by vacary** [comment]
@fperignon do you think that we can still merge this branch ?

**Comment by fperignon** [comment]
> Le 9 janv. 2019 à 10:01, Vincent Acary <notifications@github.com> a écrit :
> 
> @fperignon <https://github.com/fperignon> do you think that we can still merge this branch ?
> 
> 

no we can’t 
It’s too old and completely outdated regarding the current version of siconos.

I need to review it

**Comment by vacary** [comment]
ok, so I close the PR

**Pull request closed without merging**
