### PR TITLE
[swig] fixes for swig 4 (hope swig-3 still works)

### LINKED ISSUE #310: Swig 4 errors
Siconos does not work with Swig4.

### PR DESCRIPTION
**Pull request by xhub**
This may close #310 Still need to be thoroughly tested. Let's hope CI runs on that one.

There is quite some cleanup with descriptors, which is good.

### CODE REVIEW

**Comment by vacary** [comment]
Thank you @xhub . Very quick patch !!
For the moment, it seems that we introduce new compilation bug. 
When it will be fixed, we will merge it into the repo on gricad to avoid mirroring problems.

**Comment by xhub** [comment]
Sounds good. I had it for a few weeks, I forgot to submit it. There may be
incompatibilities with swig-3, it can be smoothed out.
Is there any CI with a CDash working?

>

**Comment by xhub** [comment]
I think that the patch is now complete. The 2 failures on travis are due to timeouts on anything printed.

**Comment by vacary** [comment]
Yes, It seems ok. I propose to merge it on gitlab gricad to mirroring problems.

**Comment by xhub** [comment]
I am fine with it :) just take the easiest path. Should I create a PR on
gricad then?

**Comment by vacary** [comment]
By merging on gricad gitlab, it closes the PR automatically by mirroring

**Pull request merged**
